# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mt4EZ0CZjd0tcGa29kfSbyc9VkhJrCmw

# Exempo de Arvore de Decisão

## Importa as bibliotecas
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
)

# from sklearn.tree import export_graphviz
# import graphviz
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

"""
## Importa o banco de dados"""

base = pd.read_csv("insurance.csv")

"""## Elimina os dados NaN dos dados"""

base = base.dropna()
base

"""## Dropa a coluna Unnamed: 0"""

base = base.drop("Unnamed: 0", axis=1)
base

"""## Define a variavel dependente e as independentes"""

y = base.iloc[:, 7].values
X = base.iloc[
    :,
    [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
    ],
].values

"""## Encodifica os dados"""

labelencoder = LabelEncoder()

for i in range(X.shape[1]):
    if X[:, i].dtype == "object":
        X[:, i] = labelencoder.fit_transform(X[:, i])

"""## Separa os dados para treinamento e teste"""

# X idependentes
# y dependente
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(
    X, y, test_size=0.3, random_state=1
)

"""## Cira o modelo de arvore de decisão"""

# Acuracia: 0.87, precisão: 0.87, Recall: 0.87, F1: 0.87
# modelo = RandomForestClassifier(n_estimators=500, random_state=1)
# Acuracia: 0.86, precisão: 0.85, Recall: 0.86, F1: 0.85
# modelo = RandomForestClassifier(n_estimators=500, random_state=0, max_depth=12, max_leaf_nodes=12)
modelo = RandomForestClassifier(
    n_estimators=500, random_state=0, max_depth=20, max_leaf_nodes=12
)
modelo.fit(X_treinamento, y_treinamento)

"""### Visualização da Arvore"""

# impressão
tree_index = 0
tree_to_visualize = modelo.estimators_[tree_index]
plt.figure(figsize=(20, 10))
plot_tree(
    tree_to_visualize,
    filled=True,
    feature_names=base.columns,
    class_names=True,
    rounded=True,
)
plt.show()

"""## Testes"""

previsoes = modelo.predict(X_teste)

accuracy = accuracy_score(y_teste, previsoes)
precision = precision_score(y_teste, previsoes, average="weighted")
recall = recall_score(y_teste, previsoes, average="weighted")
f1 = f1_score(y_teste, previsoes, average="weighted")

print(f"Acuracia: {accuracy}, precisão: {precision}, Recall: {recall}, F1: {f1}")

report = classification_report(y_teste, previsoes)
print(report)
